// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVE0KdoCd0iNhIdQz0Y3C8f4AFWCmiH0k',
    appId: '1:750714659660:web:279b3162aaca5471a725e9',
    messagingSenderId: '750714659660',
    projectId: 'ecommerce-app-a6c0c',
    authDomain: 'ecommerce-app-a6c0c.firebaseapp.com',
    storageBucket: 'ecommerce-app-a6c0c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAEBHo2R3BktEbczcXN0ENQQ_Jk58GLA4',
    appId: '1:750714659660:android:570bd9f6a081445fa725e9',
    messagingSenderId: '750714659660',
    projectId: 'ecommerce-app-a6c0c',
    storageBucket: 'ecommerce-app-a6c0c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCU8zwOz3SGlas4r_TU_9OZ-dJJTp7q33U',
    appId: '1:750714659660:ios:eebd97160a9609a4a725e9',
    messagingSenderId: '750714659660',
    projectId: 'ecommerce-app-a6c0c',
    storageBucket: 'ecommerce-app-a6c0c.appspot.com',
    iosBundleId: 'com.example.summer1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCU8zwOz3SGlas4r_TU_9OZ-dJJTp7q33U',
    appId: '1:750714659660:ios:eebd97160a9609a4a725e9',
    messagingSenderId: '750714659660',
    projectId: 'ecommerce-app-a6c0c',
    storageBucket: 'ecommerce-app-a6c0c.appspot.com',
    iosBundleId: 'com.example.summer1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVE0KdoCd0iNhIdQz0Y3C8f4AFWCmiH0k',
    appId: '1:750714659660:web:f7a178bb30ae5278a725e9',
    messagingSenderId: '750714659660',
    projectId: 'ecommerce-app-a6c0c',
    authDomain: 'ecommerce-app-a6c0c.firebaseapp.com',
    storageBucket: 'ecommerce-app-a6c0c.appspot.com',
  );
}
